### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by robfordww** [zce/fearless#143]
A clone followed by "npm install" currently returns this:

![image](https://user-images.githubusercontent.com/24738409/163881981-9a0dc19c-a6cc-47f0-8f9e-154e2054dd84.png)

**Comment by robfordww** [comment]
```
package.json:
-    "eslint": "8.5.0",
+    "eslint": "^8.13.0",
```

seems to solve it

**Comment by zce** [comment]
fixed
